notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

# os:
#   - linux
#   - osx
sudo: required
dist: trusty
group: edge

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install codecov
  - pip install pytest-cov
  - pip install .
  - pip install -e .

script:
  - pytest --cov=./src/chemcoord tests

after_success:
  - codecov
