package:
    name: chemcoord
    version: {{ GIT_DESCRIBE_TAG|replace("v","") }}

source:
    git_url: ../

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - pandas >=0.20
    - numba >=0.35
    - sortedcontainers
    - sympy
    - six

  run:
    - python
    - numpy
    - scipy
    - pandas >=0.20
    - numba >=0.35
    - sortedcontainers
    - sympy
    - six

about:
  home: http://chemcoord.readthedocs.io/
  license: LGPLv3
  license_file: LICENSE.md
